### ISSUE TITLE
This is great - good job

### ISSUE THREAD

**Issue by clearsitedesigns** [supermedium/aframe-environment-component#10]
This is really neat. I also was working on a system for rapid prototyping. I may try and add some interior office spaces, and such into the mix here.

**Comment by feiss** [comment]
thanks a lot! very kind of you. Hmm.. interiors.. that could be nice too, although maybe in another special component? because almost nothing from the environment component would be used in interior..

maybe an `aframe-interior-component` ? I'd love to help! :)

**Comment by clearsitedesigns** [comment]
There is a plugin called rooms that I've merged into yours to do some interesting things with inside and outside worlds - at least for prototying
