### ISSUE TITLE
ground is flattened

### ISSUE THREAD

**Issue by jayber** [supermedium/aframe-environment-component#22]
Been using environment component for a while with no probs now suddenly the ground appears squashed into a strip. When page loads, environment displays correctly, but when javascript used to set the "preset" property to change the displayed environment, the new environment is squashed. Had been working fine.
![squashed](https://user-images.githubusercontent.com/2474334/31311459-6a56a588-aba4-11e7-8c80-8a23c72c71d7.png)

**Comment by jayber** [comment]
Just used the previous version and that still works, so looks like caused by most recent update :-)

**Comment by feiss** [comment]
Ok, reverted to previous version. Thanks a lot!
