### ISSUE TITLE
WASD Keys acting oddly

### ISSUE THREAD

**Issue by stevel4857** [supermedium/aframe-environment-component#26]
I added <a-scene look-controls wasd-controls="fly: true"> to the scene along with a large gltf 2 model. The WASD keys seem to be moving oddly or flying doesn't happen at all. 

My test is here: http://www.cablecenter.org/vr/network/

The good thing is that this is amazing. Possibly I'm placing the gltf wrong?

**Comment by feiss** [comment]
Nice scene! :D

What is wrong about WASD? it works perfect for me. What browser are you
using?

**Comment by stevel4857** [comment]
I managed to fix the WASD keys by removing the code completely. I need to
have the ability to fly="true" but that doesn't work. So, when flying the
WASD keys don't seem to work correctly.
I won't have time to setup am example until end of next week now. I assume
the GLTF model does something. The environment component and network
component work fine until I add the gltf and then flying.

Does this make more sense?

Steve Luiting
http://sluiting.weebly.com
P: 720.563.9377

**Comment by stevel4857** [comment]
I can use it as it is now but I wanted the ability to move to the second
floor by flying.

Steve Luiting
http://sluiting.weebly.com
P: 720.563.9377

**Comment by feiss** [comment]
outdated
