### ISSUE TITLE
white circle when using <entity camera>

### ISSUE THREAD

**Issue by rmrbytes** [supermedium/aframe-environment-component#30]
I have been trying your environment-component which I found to be very configurable. However, am facing a problem when I use the `<a-entity camera look-controls wasd-controls></a-entity>`. This causes a white circle to be formed over the ground level. Removing this entity shows up your configured sky as well as ground. Do I need to set some attribute in the camera? thanks.

R

**Comment by vincentfretin** [comment]
@rajnikantmrao You can use `<a-camera />` which has a default user-height of 1.6. If you use the camera component yourself, this defaults to 0, so you need this: `<a-entity camera="user-height:1.6" look-controls wasd-controls />`. That's all.

**Comment by rmrbytes** [comment]
thanks.

just love the component. thanks.

R
