### ISSUE TITLE
Skytype:atmosphere with changed colors

### ISSUE THREAD

**Issue by rmrbytes** [supermedium/aframe-environment-component#33]
Is there a way we can use the *skytype:atmosphere* and change the colors. I notice that the default color is blue and based on the sunPosition it changes. I am keen to use this component in a pure black & white (with shades of gray) scene. Is that possible?

**Comment by feiss** [comment]
Nope, there's no way. But as a quick fix you could edit the atmosphere shader and at the end, return the same values for r,g,b.

**Comment by rmrbytes** [comment]
Ok. Thanks. Did you mean the skyshader or is the atmosphere shader a different component? I tried looking at the skyshader but did not find any color settings (or did not recognise them).

**Comment by feiss** [comment]
Yes, sorry, skyShader. This line is the color output.

https://github.com/feiss/aframe-environment-component/blob/master/index.js#L1162

Try

float gray= (retColor.r + retColor.g + retColor.b) / 3.0;
gl_FragColor.rgb = vec3(gray, gray, gray);

**Comment by rmrbytes** [comment]
Great. It worked. Thanks.

**Comment by feiss** [comment]
Nice! :)
