### ISSUE TITLE
Customization in preset.

### ISSUE THREAD

**Issue by TitikshaDaga** [supermedium/aframe-environment-component#34]
Hi @feiss I want to know how can I customize preset instead of using inbuilt presets. I want to make a room instead of using forest, desert, etc.

-Thanks

**Comment by feiss** [comment]
Well, you can hide the parts of the environment that you don't need (in your case, ` dressing:none` ), and load the model of the room using any aframe object loader (https://aframe.io/docs/0.7.0/introduction/models.html)

**Comment by TitikshaDaga** [comment]
@feiss still not able to load image in the background. I am using environment for loading background 360 view.

-Thanks.

**Comment by feiss** [comment]
Are you sure you need the environment component? I think it would be simpler if you just use a custom ground, room and sky..

For a 360, use aframe's `<a-sky>`
