### ISSUE TITLE
Lighting changes have no effect

### ISSUE THREAD

**Issue by anselanza** [supermedium/aframe-environment-component#35]
I am trying to alter the default lighting in an environment (I'd like to add my own lighting), but setting `lighting: none` appears to have no effect whatsoever.

Here is `environment="preset: arches"`
![screen shot 2018-02-23 at 17 10 27](https://user-images.githubusercontent.com/3015222/36604030-e2b2871a-18bc-11e8-9a05-13ed26e2e5f9.png)
... and here is `environment="preset: arches; lighting: none"`
![screen shot 2018-02-23 at 17 10 39](https://user-images.githubusercontent.com/3015222/36604041-e9557172-18bc-11e8-88eb-5ac4252dfe20.png)

I can also see in the A-Frame Inspector that visibility of the lights in the scene has not been changed at all.

This is curious because looking through the `index.js` file it appears as if the visibility of lights *should* change on this setting.

**Comment by feiss** [comment]
Hmm yeah it should! I'll take a look as soon as I can.

**Comment by anselanza** [comment]
Thank you!

**Comment by feiss** [comment]
hah, a bit too late I'm afraid! but I've fixed this (just by forcing the update) 
606410bef22a77b91384efd58e8083c7b7378139

**Comment by anselanza** [comment]
Ah, great thank you!
