### ISSUE TITLE
Question: Infinite terrain

### ISSUE THREAD

**Issue by mhebrard** [supermedium/aframe-environment-component#36]
Hello, Is it possible to use this component to manage an infinite environment ?
I notice that the camera can move until the end of the ground.
Is there a way to generate "the next plane" when camera is close to one edge ?
it would be awesome ;)

**Comment by feiss** [comment]
nope! sorry, at the moment it's only intended for using as a background, while the user stays pretty still around the center play area..

(it would be cool having that feature, indeed.. 👍 )
