### ISSUE TITLE
Stars animation 

### ISSUE THREAD

**Issue by DenadaPatron** [supermedium/aframe-environment-component#41]
I have used a 'suntime' component to animate my sun of the 'starry' environment, but I am struggling to anime stars in a similar manner. Everytime I try to animate stars, it creates another entity instead of animating environment's stars. Kind regards. 

<a-entity id="stars"></a-entity>

**Comment by feiss** [comment]
Sorry for the delay :(

animating stars will be a nice effect, cool :)

You will find a child entity with id=`stars` inside the environment entity. You just have to rotate it. Something like: `document.getElementById('stars').setAttribute('rotation', ...)` should work.

Have in mind that, for optimization purposes, stars are created only above the horizont, not below it, so if you rotate the stars in x or z where will be no more stars to show. You can force creating stars all around by editing the environment component and changing line 966:

`v.set(this.random(i + 23) - 0.5, this.random(i + 24), this.random(i + 25) - 0.5);`
by
`v.set(this.random(i + 23) - 0.5, this.random(i + 24) - 0.5, this.random(i + 25) - 0.5);`

**Comment by DenadaPatron** [comment]
Hello,

thanks a lot for your response. However, this is now irrelevant as I have
already submitted my honours project.
If curious what I have achieved with aframe please see the link below:

http://enko.design/bothyvr

Kind regards,
Arturas

**Comment by vesper8** [comment]
@DenadaPatron I'm curious to see what you've achieved but your link doesn't work (anymore). Any chance you have it posted somewhere else.. or maybe you have the code on github or another code sandbox? Thanks!
