### ISSUE TITLE
`particle-system-component` does not work with a positive `fog` value

### ISSUE THREAD

**Issue by dsinni** [supermedium/aframe-environment-component#46]
I'm not sure if this is more of an issue for `aframe-environment-component` or `aframe-particle-system-component`, but particles will not display if `fog: 0` is not used.

Kind of a bummer to not be able to combine these effects.

**Comment by feiss** [comment]
yup you are right, it's a shame not being able to combine both, but i'm afraid it's a problem of the particle system that doesn't work with fog on. Read more on: https://github.com/IdeaSpaceVR/aframe-particle-system-component/issues/26

**Comment by vesper8** [comment]
not only will they not display but it causes a crash and all javascript stops working

**Comment by vesper8** [comment]
could anyone explain how I can detect if fog is active? I have a hotkey that cycles environment presets and another hotkey to toggle particles on/off. I would like to detect if the current environment contains fog so I don't try to enable particles which causes a hard crash
