### ISSUE TITLE
Adjust for gammaOutput=true, gammaFactor=2.2

### ISSUE THREAD

**Issue by donmccurdy** [supermedium/aframe-environment-component#49]
Per https://github.com/aframevr/aframe/issues/3509#issuecomment-392650510, I think that we should change A-Frame's default colorspace and gammaFactor. The current values (and three.js defaults) are not so artist-friendly. The environment component is optimized for `gammaOutput=false`, and is much too bright otherwise:

![screen shot 2018-06-02 at 11 39 41 am](https://user-images.githubusercontent.com/1848368/40879777-11583d0e-665a-11e8-90ca-1ab649f45027.png)

One of two changes would be good:

- have A-Frame assume that when the colorSpace is sRGB, all `material.color` values are also sRGB, and convert them to linear before passing into three.js.
- update the environment component to use linear colors as three.js expects

Any preference on these?

**Comment by feiss** [comment]
rough question, sorry but I don't have the technical background to answer :/

**Comment by donmccurdy** [comment]
No worries! Can track it in aframevr/aframe#3509 (comment) then.

**Comment by feiss** [comment]
Thanks!
