### ISSUE TITLE
Use objects in scene

### ISSUE THREAD

**Issue by melissamcewen** [supermedium/aframe-environment-component#53]
I love the objects here like the trees, is there any way to easily add them to my scenes? I looked at the code and see they are made up of faces and vertices, but not sure how you would load them and how to format the file. Are they from Blender?

**Comment by feiss** [comment]
Sorry, but they are geometry generated on the fly, procedurally, so they don't come from a traditional 3d model. But those trees are quite simple to build! If you start from a sphere or cylinder..

**Comment by feiss** [comment]
this tutorial can help too: https://www.youtube.com/watch?v=YRgcXnd1Wl4&app=desktop
