### ISSUE TITLE
active set to false doesn't remove the environment

### ISSUE THREAD

**Issue by Utopiah** [supermedium/aframe-environment-component#61]
`<a-entity  active="false" environment="preset: forest"></a-entity>`

and 
   
` <a-entity active="true" environment="preset: forest"></a-entity>`
give the same visual result.

**Comment by Utopiah** [comment]
Also seems to have problem while dynamically adding it once the scene has loaded. 

```
  var env = document.createElement("a-entity")
  env.setAttribute("environment", "preset", "forest")
  AFRAME.scenes[0].appendChild(env)
```

makes only the ground and sky shader visible, not other elements. Whereas adding `<a-entity environment="preset: forest"></a-entity>` in the scene directly works.

**Comment by jedpimentel** [comment]
try
`<a-entity environment="preset: forest; active:false"></a-entity>`

The `active` attribute needs to be placed inside the `environment` component.
Doing so programmatically would be `entity.setAttribute('environment', 'active', 'false');`, I'm getting an issue with it removing stuff that isn't part of the environment entit on active:false, which is super wierd. (most but not all geometries turned black)

**Comment by levexis** [comment]
Hello, in 1.1.0 the active flag works when the object is embedded in the page but nothing works for me from JS. I can neither make it active nor deactivate it. Even removing the element makes no difference. Is there a way to get a-frame to completely re-render?

**Comment by levexis** [comment]
Not sure what the problem was when I tried before but this is now working for me with version 1.1.0 of aframe and the environment components. I can use 
 <a-entity id="environment" environment="preset: forest"></a-entity>
document.querySelector('#environment').setAttribute('visible',true)
document.querySelector('#environment').setAttribute('environment', 'active', 'false')

**Comment by dmarcos** [comment]
As @levexis commented. This seems to be working. Make sure you're using the latest version 1.3.0 and A-Frame 1.2.0 or newer. Closing for now and reopening if necessary
