### ISSUE TITLE
Prevent adding or disable lights within environment component   

### ISSUE THREAD

**Issue by iburguera** [supermedium/aframe-environment-component#62]
I'm building a scene with custom lights and every time I add an environment component, the scene gets brighter due to the lights within the environment component.

Is there is any way to prevent adding or disable those lights to the environment component? 
I can disable them manually, but I'm wondering if there is any way of doing that by code. 

Adding this code to environment is not working
```
lighting: none   
```

![environment](https://user-images.githubusercontent.com/3015030/62387708-ad8f1e80-b55b-11e9-904b-2a9c397f7e84.png)

BR

**Comment by iburguera** [comment]
I have figure it out how to remove it. I was adding the code ``` lighting: none ```  as another entity attribute instead of adding within the environment property.

Here is how I added using Javascript if anyone is interested:

```
function entornoEscena(entorno)
{
       var sceneEl = document.querySelector('a-scene');
       var entornoEl = document.createElement('a-entity');
	
       entornoEl.setAttribute('id','entornoEscena');
       entornoEl.setAttribute('position', {x: 0, y: -0.2, z: 0});
       entornoEl.setAttribute('environment', 'preset: '+entorno+'; lighting: none');
	        
       sceneEl.appendChild(entornoEl);
}
```

You have to pass some preset (egypt,volcano,...) to the function.

**Comment by feiss** [comment]
:)
