### ISSUE TITLE
Is there a way to get the size of the world that is being created in pixels?

### ISSUE THREAD

**Issue by netgfx** [supermedium/aframe-environment-component#68]
I'm looking into popularizing the environment with trees based on perlin noise but I need to know the size of the world to make it more specific.

Thanks.

**Comment by feiss** [comment]
The ground plane is 200x200 meters, and the sky dome's diameter is 400 meters. If your perlin noise returns values between 0,1, you can place your trees at `perlin * 200`

**Comment by netgfx** [comment]
awesome thanks!
