### ISSUE TITLE
Cannot read property 'position' of undefined     at i.updateGround (aframe-environment-component.js:523)

### ISSUE THREAD

**Issue by andreeapav09** [supermedium/aframe-environment-component#71]
![image](https://user-images.githubusercontent.com/42643862/122656152-b9d8f080-d160-11eb-95c8-37f33dd4ecb2.png)

I keep getting this error when I add the environment-component and the only thing that changes in my application is the sky. I don't get the trees in the forest preset for example.

![image](https://user-images.githubusercontent.com/42643862/122656198-0ae8e480-d161-11eb-9e3a-95cb41b228aa.png)
There are all my imported scripts in this scene.

Thanks

**Comment by andreeapav09** [comment]
I created a separate file only with environment-component and aframe 1.1.0. Same probless

I guess the aframe-environment-component is not compatible with aframe 1.1.0

**Comment by DrMicPhys** [comment]
Ran into the same problem (with things I swear were working before) but was using aframe 1.0.4, but when I switched to aframe 1.2.0 the environment component seems to be working again.

**Comment by dmarcos** [comment]
Make sure you are using the 1.3.0 version of the environment component with A-Frame 1.2.0 or newer. None of this issues should happen. Closing for now and reopening if necessary
