### ISSUE TITLE
Change size of the environment 

### ISSUE THREAD

**Issue by KawanaS** [supermedium/aframe-environment-component#75]
How to change the width or the size of the environment? I have tried using scaling, but that distorts the sky and other features.

**Comment by VictorSOS** [comment]
I would also like to know this. How to change size of the environment sphere and the ground grid?

**Comment by RodrigoWebDev** [comment]
Me too. Searching in the source code I saw there is a variable called STAGE_SIZE that was hard coded

![image](https://user-images.githubusercontent.com/30677819/167242239-cb012453-caee-4f82-8eb5-5af16b88a0b0.png) 
https://github.com/supermedium/aframe-environment-component/blob/master/index.js

I will work on this when I have some time :)

**Comment by kylebakerio** [comment]
Yeah, I have hacked it before to modify stage size and then update. that works for me.

**Comment by tntmonty** [comment]
Yeah, I think I'm having issues with STAGE_SIZE as well as some objects with a cube-env-map aren't working correct, and it seems to be related to if they're near the sky sphere. I didn't think it should be an issue, and only happens on my VR device, but maybe it does affect it? Maybe should be a param on the component as it is for <a-sky>?
