### ISSUE TITLE
Can you update the version of aFrame to 1.3.0?

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [supermedium/aframe-environment-component#80]
I am wanting to use the latest version, but when I try to convert it it won't work. Can you try updating it?

**Comment by vincentfretin** [comment]
What issue do you have? What do you mean by convert it?
aframe-environment-component 1.3.1 is working correctly with aframe 1.3.0 and current aframe master with threejs r144.

**Comment by TheRealDigitalMaster** [comment]
Ok just making sure because my updated version looks different. Thanks :)

**Comment by dmarcos** [comment]
Closing this. there are no actions to be taken.
