### ISSUE TITLE
Decreasing preset dressingAmount for certain preset (e.g., forest)

### ISSUE THREAD

**Issue by ngokevin** [supermedium/aframe-environment-component#9]
My GTX 1080 desktop lags in the forest preset which has 500 trees. Reducing it to 100 feels better.

**Comment by feiss** [comment]
Mmm.. not sure what to do about this. Maybe 500 is ok for the 90% of people trying, or maybe 100 is still too demanding for many..

**Comment by ngokevin** [comment]
Maybe someone else can try in VR to see how it feels? I mentioned I have a full GTX1080 on a desktop, top-end GPU, and it was chopping up there. I can try again later.
