### ISSUE TITLE
aframe 1.5.0 THREE.Material: parameter 'glslVersion' has value of undefined.

### ISSUE THREAD

**Issue by vincentfretin** [supermedium/aframe-environment-component#96]
With aframe 1.5.0, we have a warning "THREE.Material: parameter 'glslVersion' has value of undefined."
I didn't quite follow the threejs changes wth glslVersion. I know @mrxz you participated in the discussion around this in aframe repo, you may now how to remove the warning and keep it compatible with both 1.4.2 and 1.5.0.

**Comment by mrxz** [comment]
This seems to be an oversight in the changes from https://github.com/aframevr/aframe/pull/5328. Quite surprising given the many iterations, discussion and testing that took place on it. I'd assume this warning would've caught the attention at some point, but alas.

Basically A-Frame now falls back to `undefined` for `glslVersion` in case of non-raw shaders ([shader.js#L58](https://github.com/aframevr/aframe/blob/master/src/core/shader.js#L58)). However the default value in Three.js is `null` ([ShaderMaterial.js#L53](https://github.com/mrdoob/three.js/blob/dev/src/materials/ShaderMaterial.js#L53)). Fix is straightforward, but needs to happen in A-Frame, will create a PR for it shortly

**Comment by vincentfretin** [comment]
Thanks you! The warning will be fixed in aframe 1.5.1 then.
